### ISSUE TITLE
Question about rescale_L 

### ISSUE THREAD

**Issue by SeanChenxy** [hongsukchoi/Pose2Mesh_RELEASE#39]
https://github.com/hongsukchoi/Pose2Mesh_RELEASE/blob/e91bdd69077e964c5591f7c52b6f484d5180bd12/lib/coarsening.py#L32
Hi, thank you for sharing the code. I have a question about rescale_L. Why not use `L /= lmax * 2` rather than `L = 2.0*L / lmax`? Looking forward your reply.

**Comment by hongsukchoi** [comment]
hi, i followed the code here: https://github.com/3d-hand-shape/hand-graph-cnn/blob/master/hand_shape_pose/util/coarsening.py

I think it doesn’t matter, since the purpose of rescaling is to prevent value explosion during chebyshev conv. With the current code, it is the eigenvalue of laplacian matrices are still bounded in [-1,1]

**Comment by SeanChenxy** [comment]
Get it. Thanks a lot.
